### PR TITLE
added currency and modification methods

### PR DESCRIPTION
**Pull request by CheesyPotatoes69**
Added a credit variable and methods to increase currency and spend it. Added into the levelManager script.

### CODE REVIEW

**Review by antoshNikolak — CHANGES_REQUESTED** [review]
Can you please refactor your code into a money manager script so that the code follows SOLID principles?

**Comment by CheesyPotatoes69** [comment]
added a new credit manager script.

**Comment by CheesyPotatoes69** [comment]
Added a currency prefab that will go in the level later. Also added a line in DamageHandler to increase money when mouse is killed.
image

**Comment by CheesyPotatoes69** [comment]
credits should now be fully implemented.
https://github.com/Project-Pixel-UoS/Chef-s-last-stand/assets/124886564/94c536ae-7db5-46ea-b711-a4033c45bee8

**Review by antoshNikolak — APPROVED** [review]

**Pull request merged**
